language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node-mocha-star' ]; then cd .. && eval "mv $currentfolder generator-node-mocha-star" && cd generator-node-mocha-star; fi

